#!/bin/bash
#SBATCH --job-name test1
#SBATCH --qos standard
#SBATCH --time 2-0:00:00
#SBATCH --account dp208
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=8
#SBATCH --partition=gpu
#SBATCH --gres=gpu:4
#SBATCH --output=%x.%j.out
#SBATCH --error=%x.%j.err

module purge
module load cuda/11.4.1  openmpi/4.1.1-cuda11.4.1  ucx/1.12.0-cuda11.4.1

export LD_LIBRARY_PATH=/home/dp208/dp208/dc-forz1/grid/prefix/lib:/mnt/lustre/tursafs1/apps/basestack/cuda-11.4.1/ucx/1.12.0-cuda11.4.1/lib:/mnt/lustre/tursafs1/apps/basestack/cuda-11.4.1/openmpi/4.1.1-cuda11.4.1/lib:/mnt/lustre/tursafs1/apps/cuda/11.4.1/lib64/



export OMP_NUM_THREADS=4
export OMPI_MCA_b56tl=^uct,openib
export UCX_TLS=gdr_copy,rc,rc_x,sm,cuda_copy,cuda_ipc
export UCX_RNDV_SCHEME=put_zcopy
export UCX_RNDV_THRESH=16384
export UCX_IB_GPU_DIRECT_RDMA=yes
export UCX_MEMTYPE_CACHE=n

STARTTRAJ=0
NSTEPS=70

mpirun -np 1 -x LRANK=0 -x LD_LIBRARY_PATH  --bind-to none ./wrappersimple.sh ./Test_hmc_Sp_Wilson_4_2ASFermionGauge --StartingType ColdStart --StartingTrajectory ${STARTTRAJ} --grid 8.8.8.8 --mpi 1.1.1.1  --accelerator-threads 8 --Trajectories 1500 --Thermalizations 400 --beta 5.6 --fermionmass -1.4 --nsteps ${NSTEPS} --tlen 1.0 --savefreq 1 --serialseed "11 12 13 14 15" --parallelseed "16 17 18 19 20" > hmc_nf4_${SLURM_JOB_ID}_b56-am14.out &

mpirun -np 1 -x LRANK=1 -x LD_LIBRARY_PATH  --bind-to none ./wrappersimple.sh ./Test_hmc_Sp_Wilson_4_2ASFermionGauge --StartingType ColdStart --StartingTrajectory ${STARTTRAJ} --grid 8.8.8.8 --mpi 1.1.1.1  --accelerator-threads 8 --Trajectories 1500 --Thermalizations 400 --beta 5.6 --fermionmass -1.3 --nsteps ${NSTEPS} --tlen 1.0 --savefreq 1 --serialseed "11 12 13 14 15" --parallelseed "16 17 18 19 20" > hmc_nf4_${SLURM_JOB_ID}_b56-am13.out &

mpirun -np 1 -x LRANK=2 -x LD_LIBRARY_PATH  --bind-to none ./wrappersimple.sh ./Test_hmc_Sp_Wilson_4_2ASFermionGauge --StartingType ColdStart --StartingTrajectory ${STARTTRAJ} --grid 8.8.8.8 --mpi 1.1.1.1  --accelerator-threads 8 --Trajectories 1500 --Thermalizations 400 --beta 5.6 --fermionmass -1.2 --nsteps ${NSTEPS} --tlen 1.0 --savefreq 1 --serialseed "11 12 13 14 15" --parallelseed "16 17 18 19 20" > hmc_nf4_${SLURM_JOB_ID}_b56-am12.out &

mpirun -np 1 -x LRANK=3 -x LD_LIBRARY_PATH  --bind-to none ./wrappersimple.sh ./Test_hmc_Sp_Wilson_4_2ASFermionGauge --StartingType ColdStart --StartingTrajectory ${STARTTRAJ} --grid 8.8.8.8 --mpi 1.1.1.1  --accelerator-threads 8 --Trajectories 1500 --Thermalizations 400 --beta 5.6 --fermionmass -1.1 --nsteps ${NSTEPS} --tlen 1.0 --savefreq 1 --serialseed "11 12 13 14 15" --parallelseed "16 17 18 19 20" > hmc_nf4_${SLURM_JOB_ID}_b56-am11.out &

wait
